### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by devhn** [yireo/Yireo_GoogleTagManager2#1]
Hi,

i've installed Tag Manager on Magento 2.0.4. and upon enabling it within the administration (observer) it gives the following error:

`Fatal error: Uncaught Error: Call to a member function getNameInLayout() on null in /var/www/html/site/app/code/Yireo/GoogleTagManager2/Observer/CoreLayoutRenderElement.php:45 Stack trace: #0 /var/www/html/site/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Yireo\GoogleTagManager2\Observer\CoreLayoutRenderElement->execute(Object(Magento\Framework\Event\Observer)) #1 /var/www/html/site/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Yireo\GoogleTagManager2\Observer\CoreLayoutRenderElement), Object(Magento\Framework\Event\Observer)) #2 /var/www/html/site/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #3 /var/www/html/site/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('core_layout_ren...', Array) #4 /var/www/html/site/vendor/magento/framework/View/Layout.php( in /var/www/html/site/app/code/Yireo/GoogleTagManager2/Observer/CoreLayoutRenderElement.php on line 45`

**Comment by yireo** [comment]
Thanks for the feedback. Most likely you are using the insertion method "Observer", you might try the "Layout" method as well. In any case, I've now added a fix for this. It seems the event parameters have changed some time ago.

**Comment by bb8d** [comment]
Yes, error was shows upon using the obvserver method. When using xml i get:

`The options you selected are not available.
#0 /var/www/html/site/vendor/magento/module-bundle/Model/Product/Type.php(280): Magento\Bundle\Model\Product\Type->getSelectionsByIds(Array, Object(Magento\Catalog\Model\Product\Interceptor))
#1 /var/www/html/site/vendor/magento/module-catalog/Model/Product.php(1892): Magento\Bundle\Model\Product\Type->getSku(Object(Magento\Catalog\Model\Product\Interceptor))
#2 /var/www/html/site/var/generation/Magento/Catalog/Model/Product/Interceptor.php(1246): Magento\Catalog\Model\Product->getSku()
#3 /var/www/html/site/vendor/magento/module-quote/Model/Quote/Item.php(420): Magento\Catalog\Model\Product\Interceptor->getSku()
#4 /var/www/html/site/vendor/magento/module-quote/Model/ResourceModel/Quote/Item/Collection.php(256): Magento\Quote\Model\Quote\Item->setProduct(Object(Magento\Catalog\Model\Product\Interceptor))
#5 /var/www/html/site/vendor/magento/module-quote/Model/ResourceModel/Quote/Item/Collection.php(169): Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_assignProducts()
#6 /var/www/html/site/vendor/magento/framework/Data/Collection/AbstractDb.php(579): Magento\Quote\Model\ResourceModel\Quote\Item\Collection->_afterLoad()
#7 /var/www/html/site/vendor/magento/framework/Data/Collection/AbstractDb.php(550): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#8 /var/www/html/site/vendor/magento/framework/Data/Collection.php(820): Magento\Framework\Data\Collection\AbstractDb->load()
#9 /var/www/html/site/vendor/magento/module-quote/Model/Quote.php(1364): Magento\Framework\Data\Collection->getIterator()
#10 /var/www/html/site/app/code/Yireo/GoogleTagManager2/Block/Quote.php(32): Magento\Quote\Model\Quote->getAllItems()
#11 /var/www/html/site/app/code/Yireo/GoogleTagManager2/Block/Quote.php(52): Yireo\GoogleTagManager2\Block\Quote->getItemsAsArray()
#12 [internal function]: Yireo\GoogleTagManager2\Block\Quote->getItemsAsJson()
#13 /var/www/html/site/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array)
#14 /var/www/html/site/app/code/Yireo/GoogleTagManager2/view/frontend/templates/quote.phtml(21): Magento\Framework\View\TemplateEngine\Php->__call('getItemsAsJson', Array)
#15 /var/www/html/site/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/m...')
#16 /var/www/html/site/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Yireo\GoogleTagManager2\Block\Quote), '/var/www/html/m...', Array)
#17 /var/www/html/site/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/html/m...')
#18 /var/www/html/site/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#19 /var/www/html/site/app/code/Yireo/GoogleTagManager2/Helper/Data.php(321): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /var/www/html/site/app/code/Yireo/GoogleTagManager2/Helper/Data.php(224): Yireo\GoogleTagManager2\Helper\Data->addQuote('               ...')
#21 /var/www/html/site/app/code/Yireo/GoogleTagManager2/Block/Script.php(25): Yireo\GoogleTagManager2\Helper\Data->getHeaderScript()
#22 [internal function]: Yireo\GoogleTagManager2\Block\Script->getScript()
#23 /var/www/html/site/vendor/magento/framework/View/TemplateEngine/Php.php(82): call_user_func_array(Array, Array)
#24 /var/www/html/site/app/code/Yireo/GoogleTagManager2/view/frontend/templates/script.phtml(14): Magento\Framework\View\TemplateEngine\Php->__call('getScript', Array)
#25 /var/www/html/site/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/m...')
#26 /var/www/html/site/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Yireo\GoogleTagManager2\Block\Script), '/var/www/html/m...', Array)
#27 /var/www/html/site/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/html/m...')
#28 /var/www/html/site/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Framework\View\Element\Template->_toHtml()
#29 /var/www/html/site/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#30 /var/www/html/site/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('googletagmanage...')
#31 /var/www/html/site/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('googletagmanage...')
#32 /var/www/html/site/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('googletagmanage...')
#33 /var/www/html/site/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('googletagmanage...', true)
#34 /var/www/html/site/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('googletagmanage...')
#35 /var/www/html/site/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('after.body.star...')
#36 /var/www/html/site/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('after.body.star...')
#37 /var/www/html/site/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('after.body.star...')
#38 /var/www/html/site/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('after.body.star...', true)
#39 /var/www/html/site/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('after.body.star...')
#40 /var/www/html/site/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#41 /var/www/html/site/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#42 /var/www/html/site/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#43 /var/www/html/site/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#44 /var/www/html/site/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#45 [internal function]: Magento\Framework\View\Layout->getOutput()
#46 /var/www/html/site/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#47 /var/www/html/site/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#48 /var/www/html/site/vendor/magento/framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#49 /var/www/html/site/vendor/magento/framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#50 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#51 /var/www/html/site/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#52 /var/www/html/site/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#53 /var/www/html/site/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#54 /var/www/html/site/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#55 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#56 /var/www/html/site/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#57 /var/www/html/site/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#58 /var/www/html/site/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#60 /var/www/html/site/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#61 /var/www/html/site/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#62 /var/www/html/site/vendor/magento/framework/App/Http.php(119): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#63 /var/www/html/site/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#64 /var/www/html/site/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#65 {main}`

This also happens with updated version. It seems as an xml issue because if i delete body referenced container and block inside the default.xml the page loads fine.

**Comment by yireo** [comment]
Hi, strange. I can replicate this issue on a fresh environment, but not on existing environments. We have done quite some refactoring anyway, so could you see if version 0.2.3 (latest) works for you?

**Comment by devhn** [comment]
It works with the latest version (0.2.3), thanks :)
