### ISSUE TITLE
(Suggestion) More logical place for module configuration

### ISSUE THREAD

**Issue by koenner01** [yireo/Yireo_GoogleTagManager2#10]
Not really an issue but more of a request/suggestion;

Currently the configuration settings are placed under Advanced.
For us (and our marketeers) this doesn't really seem like a logical place.

Maybe you could consider moving it to "Marketing" or "Sales > Google API" ?

**Comment by jissereitsma** [comment]
Good point. Moving extension options from one place int he System Configuration to another is unfortunately really hard, because it would require a complete rewrite of a lot of code to make things backward compatible. Because of this, moving things into a subtab of "Sales > Google API" is too much work. However, the next release will be added to "Sales" instead.
