### ISSUE TITLE
[Bug] Product category information in data layer is incomplete

### ISSUE THREAD

**Issue by DuckThom** [yireo/Yireo_GoogleTagManager2#138]
When looping through the categories in `Yireo\GoogleTagManager2\DataLayer\Mapper\ProductDataMapper::attachCategoriesData` only the last category is sent to the data layer.

The initial state for `$currentCategoriesCount` is 1 making the ternary in the line below return `''`. Since the count is only incremented when the statement is false, it will always return `''`.

https://github.com/yireo/Yireo_GoogleTagManager2/blob/fc4c3c3a20da135e34dd07bb58394ab64afbac88/DataLayer/Mapper/ProductDataMapper.php#L108

## Possible fix

```php
$key = 'item_category' . ($currentCategoriesCount == 1 ? '' : $currentCategoriesCount);
$data[$key] = $category->getName();

$currentCategoriesCount++;
```

**Comment by jissereitsma** [comment]
First of all, big fist-bump-to-my-forehead for seeing the code not do much. Pretty pointless loop. I think your suggestion is pretty solid, so I'll add this as a fix right away. Many thanks!

Note that you could have also created a PR for this - quite easily because it is only a single file that could edit here in the repo. Anyway, happy to include your improvement. It definitely makes sense.

**Comment by jissereitsma** [comment]
Reference https://github.com/yireo/Yireo_GoogleTagManager2/commit/f1345e5a90ea5efc9665afba43804a722b842dc0
