### ISSUE TITLE
Ecommerce Data Layer tracking with Yireo for Magento1

### ISSUE THREAD

**Issue by malek-gogoprint** [yireo/Yireo_GoogleTagManager2#164]
Hey there,

I'm not sure if this is the right place to ask this kind of questions, but I'm posting it, in case someone here can support me with my inquiries.

We've been using Yireo to push variables to the data layer for a **Magento1** ecommerce website.

Now we're working on migrating our tracking from UA to GA4. We have set things up for GA4 in Google Tag Manager, and events are being tracked properly, but the ecommerce tracking is still empty in our GA4 account (under "Reports → Monetization → Ecommerce purchases")

<img width="1509" alt="Image" src="https://github.com/yireo/Yireo_GoogleTagManager2/assets/56110378/741f78bb-c2be-4dcf-814f-5c34c9c70277">

With a bit of research, I came across [this article](https://www.digitalninjas.com/google-analytics/google-analytics-4-ga4-ecommerce-datalayer-how-is-it-different-from-ua/) that explains that the way we push variables to the data layer for GA4 is different from UA.

Since we're using Yireo to push those variables to the data layer, I assume that we'd need to upgrade our Yireo version so we push the data in the way that is supported by GA4.

So, I wanted to ask about 2 things here:

1. Do you have any tutorial or guide on what we should change in Yireo in order to get the ecommerce tracking up and running again for our Magento1 site?
2. Ideally, we'd like to keep tracking the old data layer structure in the UA account as well. So we'd like Yireo to keep pushing data to the old UA account the way it currently does, but we also want it to start tracking the new GA4 data with the new data layer structure. Is this something that's feasible? And if yes, could you please advise on how we could achieve it?

Thanks in advance for your support :)
Best,
Malek

**Comment by jissereitsma** [comment]
You refer to using "Yireo". As Yireo is a company, I don't think you are choosing the right words. Instead, you are using a "Magento 1 extension called Yireo GoogleTagManager" which is HUGE difference.

This repository is for the Magento 2 extension. The Magento 1 extension can be found here: https://github.com/yireo-magento1/Yireo_GoogleTagManager Note that because Magento 1 has been dead for years, this Magento 1 extension has been dead for years as well. It does not support GA4 and will never do, unless others are eager to extend upon it. There will be no Magento 1 support from the side of Yireo.

I'm closing this ticket here because it is not related to this repository and/or this extension. 

My personal advice would be to look for a Magento developer to see what is possible.
