### ISSUE TITLE
Compatibility with One Step Checkout from Mageplaza

### ISSUE THREAD

**Issue by web4exposure-org** [yireo/Yireo_GoogleTagManager2#168]
Hi,
We are using Mageplaza_Osc as our checkout page.
Currently I see an issue on the checkout page - javascript related.

`jquery.js:4050 jQuery.Deferred exception: Cannot read properties of undefined (reading 'isVisible') TypeError: Cannot read properties of undefined (reading 'isVisible')
    at ko.subscription._callback (/static/frontend/<vendor>/<theme>/nl_NL/Yireo_GoogleTagManager2/js/mixins/step-navigator-mixin.js:14:26)`

**Comment by jissereitsma** [comment]
This extension aims to be offering code that doesn't cause errors, so the JS error itself is now fixed in version 3.4.4: https://github.com/yireo/Yireo_GoogleTagManager2/commit/d1cd0fb168053668934a9003fc51d4914bf7709d 

However, full compatibility with Mageplaza OSC itself is a different ballgame. I'm not going to invest any money in such an extension just to add support on a voluntary basis. For the money you pay them, I would expect support from their side. Note that fixing the JS error does not mean that full compatibility is there. It simply means that the Mageplaza OSC is not compatible with the regular OSC of Magento, so somebody needs to invest time and work to make full compatibility a thing.

**Comment by web4exposure-org** [comment]
Totally understand.
I see this issue is fixed. While this issue is fixed, I get another one:
`jquery.js:4050 jQuery.Deferred exception: Cannot access 'eventData' before initialization ReferenceError: Cannot access 'eventData' before initialization
    at ko.subscription._callback (http://misteragri.test/static/frontend/Web4exposure/misteragri/nl_NL/Yireo_GoogleTagManager2/js/mixins/step-navigator-mixin.js:17:24)`

I guess the `const eventData = window.YIREO_GOOGLETAGMANAGER2_BEGIN_CHECKOUT;` needs to be placed on line 14.

**Comment by jissereitsma** [comment]
Thanks, this was a stupid type. Release 3.4.5 should fix this.
