### ISSUE TITLE
Pagination of products on category page killed by this extensions

### ISSUE THREAD

**Issue by richardreen** [yireo/Yireo_GoogleTagManager2#173]
When I install this extension and activate it then the pagination of the products on the category page(s) is not working anymore.
For example a category has 100 products and config is that 20 products should be visible on a page. So there will be then 5 pages, and also in the bottom links to the other pages. When I use this extensions then ALL products are visible on the first page. The links in the bottom are showing 5 pages. But all pages are the same, ALL products of that category. When I have a lot of products then the performance is terrible because it shows all products on that page.

When I remove this extension, that pagination is working normal again. So this issue is caused by this extension.
When I look at the console, there are no error messages or so.

I am using the latest version of this extension.

**Comment by jissereitsma** [comment]
Thanks. This sounds like a very serious issue. However, I'm unable to duplicate it anywhere else, and no one else seems to be suffering from this. So it seems logical at first that some custom-built in your Magento instance is causing this bug to arise. 

This GTM module keeps track of how many products are loaded on the page through the DI plugin `Yireo_GoogleTagManager2::getProductsFromCategoryBlockPlugin` and that's the only mechanism that touches upon listing products.

It makes sense also to report basic things like your Magento version, whether or not this happens with or without what kind of caching (FPC, block, layout). And whether other Magento modules are also creating DI plugins for the `Magento\Catalog\Block\Product\ListProduct` class. And whether your `ListProduct` class is the original Magento version or replaced with a specific extension. And whether the problem is fixed when that other extension is disabled.

**Comment by richardreen** [comment]
I never had this issue, till I installed the Googletagmanager2. Then it pups up. Disabled this extension and the problem is gone.
I real do not know what you mean with DI and so, I am not an developer but just a magento user.
So i will remove this extensions and then this problem is gone, this works for me!!

**Comment by jissereitsma** [comment]
Yes, I understand that this is not related to only a third party extension - that's not what I said either. I mentioned that I'm unable to duplicate this in a clean Magento environment. And because there are 1000s of extensions out there, I'm unable to predict which extensions would break this Yireo GoogleTagManager2 module for what reason. If disabling this module is an option, then that's an option. If it is not, and there is an issue in your specific shop, then it requires a specific mindset to solve this: Call that developer knowledge, but as a "Magento user" you definitely would need more skills than just enabling or disabling an extension. Unfortunately, I lack the time to volunteer to be a developer of your specific shop. So either, this issue remains open until somebody comes along with the same issue and the skillset to analyse this in full. Or a developer is hired (which is logical, because this happens with almost all Magento implementations). Or the issue is dropped. Unfortunately, apart from making hints on how to analyse this further as a developer, there is little I can do.

**Comment by richardreen** [comment]
ok, no problem, will remove this extension.
