### ISSUE TITLE
require is not defined in Hyva

### ISSUE THREAD

**Issue by web4exposure-org** [yireo/Yireo_GoogleTagManager2#180]
Hi,
I get the error "Uncaught ReferenceError: require is not defined" on the product page while using the Hyva theme. This module should be compatible stated on your website.

The error is raised on this point:
`<div class="product-info-main">
                            <script text="text/javascript">
                                require(['domReady!'], function() {
                                    var _learnq = window._learnq || [];
                                    _learnq.push(['track', 'Viewed Product', {`

**Comment by jissereitsma** [comment]
Dear @web4exposure-org , the code `_learnq` is not part of this Yireo module. Are you 100% sure that there is not some other module that has added this code? Because it would be very strange that you ask about the compatibility of this Yireo module, while actually the problem would be caused by a totally different module (or theme addition). Did you search for the file where this code occurs?

**Comment by web4exposure-org** [comment]
I'm so sorry! You're right, this is the Klaviyo integration and not the Yireo. I was distracted by the tracking stuff.
