### ISSUE TITLE
Possible incompatibility with Amasty Onestepcheckout (Pro)?

### ISSUE THREAD

**Issue by julianmurillosd** [yireo/Yireo_GoogleTagManager2#225]
Hi Yireo team,

This week i've been testing the Yireo GTM module (3.7.12) on a Hyva site (Magento 2.4.4-p7, PHP 8.1, Hyva version 1.3.5), which makes use of the Amasty Onestepcheckout Pro extension (version 2.3.3). 

For the checkout part, we implement the Hyva Theme Fallback, so the checkout runs on Luma in combination with the Amasty OSC extension.

All events fired up, except for the 'begin_checkout' one. Only after disabling the Amasty OSC extension, the event 'begin_checkout' fired up as expected (together with the other ones).

Maybe this is something for which you might add an official fix?

Greetings,

**Comment by jissereitsma** [comment]
Sure, which fix did you have in mind? Unfortunately, I'm unable to pay the fee of the Amasty OSC extension just to voluntarily support that paid Amasty OSC extension because it is not compatible with the standard Magento OSC.

**Comment by a-mahmoudieh** [comment]
Yes, Unfortunately Amasty one step checkout not supported!

**Comment by jissereitsma** [comment]
Sure. But again, this is a voluntary project that I run personally for free. I don't have the license and the time to invest into an extension that I don't need and know of. Please contribute instead of only earning money on top of free stuff.

I'm closing this issue, because it is not an issue of this extension. It is a lack of interest of people to contribute. Open source does **not** ask and get for free, it means collaboration. Please contribute first, then let's talk.

**Comment by a-mahmoudieh** [comment]
Yes Thank you This is nice extension and I want to contribute but I live in Iran and under heavy sanction
Do you understand it !?

**Comment by jissereitsma** [comment]
Ahm, I don't think your country or the sanctions are stopping you from contributing - you are able to access this GitHub site, so you are able to add a Pull Request as well. Likewise, the fact that you are asking about an Amasty OneStepCheckout extension is assuming that you already have that extension. So, the sanctions didn't stop you from getting that extensions either. Please note that I am just simply poor guy from The Netherlands and I'm unable to lift the sanctions for you. If open source doesn't work for you, too bad.

**Comment by a-mahmoudieh** [comment]
About Amasty extension (Yes I do not paid for it)
How can I contribute, Please guide me?

**Comment by jissereitsma** [comment]
I will respond one last time, but note: I don't need this functionality. If you need this functionality, you will need the Amasty extension. If you don't have the Amasty extension, you don't need this functionality here either. This issue was about adding Google Tag Manager support to the Amasty extension, which requires you have the extension. If you do not have that extension, there is zero that you need to do here. Just use free stuff.
