### ISSUE TITLE
RuntimeException thrown on product view

### ISSUE THREAD

**Issue by tdgroot** [yireo/Yireo_GoogleTagManager2#23]
I get the exception:
`Source class "\Yireo\GoogleTagManager2\ViewModel\Product" for "Yireo\GoogleTagManager2\ViewModel\Product\Interceptor" generation does not exist.`

When I take a look at the ViewModel directory, the Product file/class is missing indeed.

**Comment by tdgroot** [comment]
Adding the following line to `\Yireo\GoogleTagManager2\Block\Generic::getViewModel()` solves the problem for me.

``` php
    public function getViewModel()
    {
        $viewModelClass = str_replace('\Block\\', '\ViewModel\\', get_class($this));
+       $viewModelClass = preg_replace('/\\\Interceptor$/', '', $viewModelClass);

        return $this->viewModelFactory->create($viewModelClass);
    }
```

**Comment by tdgroot** [comment]
This problem only occurs when writing a plugin for either `\Yireo\GoogleTagManager2\Block\Generic`, or `\Yireo\GoogleTagManager2\Block\Product`.

**Comment by jissereitsma** [comment]
I already had the feeling it had to do with specific plugins that were trying to add something. The issue is that I'm trying to do something new here, with automatically created ViewModels - it is new behaviour that works differently in Magento 2.2, but I wanted to have something similar already in Magento 2.1. https://github.com/yireo/Yireo_GoogleTagManager2/commit/5ac692d428c52cddc6cb80eebedd227ad0062732

**Comment by tdgroot** [comment]
Great, thank you! 

Just curious - can you show me a Magento 2.2 example where this behavior is being implemented?

**Comment by jissereitsma** [comment]
I mentioned it here: https://www.yireo.com/blog/1856-viewmodels-in-magento-2
