### ISSUE TITLE
E-Commerce Value With / Without Tax

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_GoogleTagManager2#240]
In https://github.com/yireo/Yireo_GoogleTagManager2/commit/ac0ce6c553fb4e890750ff35ac05d6f7a3c15b88, the following has been fixed:

> Make sure `value` of event `purchase` is without tax and shipping

I think this makes sense. However, I think this is now inconsistent. There are multiple spots, where this is still with tax and shipping:

https://github.com/yireo/Yireo_GoogleTagManager2/blob/05da1a89bb4f075d73b6dac4596a5a80a700f29e/DataLayer/Event/Refund.php#L41

https://github.com/yireo/Yireo_GoogleTagManager2/blob/05da1a89bb4f075d73b6dac4596a5a80a700f29e/DataLayer/Tag/Order/Order.php#L44

https://github.com/yireo/Yireo_GoogleTagManager2/blob/05da1a89bb4f075d73b6dac4596a5a80a700f29e/DataLayer/Mapper/OrderDataMapper.php#L54

https://github.com/yireo/Yireo_GoogleTagManager2/blob/05da1a89bb4f075d73b6dac4596a5a80a700f29e/DataLayer/Mapper/OrderDataMapper.php#L71

Shouldn't this be updated in all places?

Also, instead of calculating this ourselves:

https://github.com/yireo/Yireo_GoogleTagManager2/blob/05da1a89bb4f075d73b6dac4596a5a80a700f29e/DataLayer/Event/Purchase.php#L60-L63

Couldn't we just use `$order->getSubtotal()`? If I am not mistaken, this is by design without tax and shipping.

**Comment by jansentjeu** [comment]
We are facing the same issue. It should be without tax and shipping costs everywhere.

**Comment by jissereitsma** [comment]
I agree with this not being consistent. The commit https://github.com/yireo/Yireo_GoogleTagManager2/commit/a74ba18acc6697d272362276f10a5b5a0041ffe3 does make this consistent.

@sprankhub As to why the subtotal was not just taken, but instead the grand total minus tax and shipping: In the past I had issues with third party extensions doing price tricks by modifying the subtotal, so that the subtotal plus tax plus shipping was not equal to the grand total. This is a long time ago. And I do not read anywhere in the Google docs that these numbers need to match up. So I'll just use the subtotal instead, which is cleanest.

**Comment by jissereitsma** [comment]
This change is now included in 3.9.3.

**Comment by jissereitsma** [comment]
I'm closing this issue because of the fixes - if needed, this could be re-opened.
