### ISSUE TITLE
Purchase event not firing since Aug 14, 2024

### ISSUE THREAD

**Issue by datavinci-audits** [yireo/Yireo_GoogleTagManager2#243]
All other ecommerce events are firing except of the purchase event. The issue was found to start from August 14, 2024. Please fix as soon as possible.

**Comment by jissereitsma** [comment]
Thanks for posting. Note that this is a voluntary project and I gain zero from helping you - so all support is done here because of developer happiness. The only one making money of your project is you. Therefore, demanding a fix as soon as possible is completely out of place. Please bring friendliness in your posts and do not put your problems in the shoes of others in such a demanding way.

I'm happy to report that the `purchase` event of this extension is still firing in all of the development sites and production sites that I'm managing. So as of yet, this seems to be a problem in your specific environment. Unfortunately, I can't volunteer to act as a maintainer of your shop, so perhaps you need to find somebody who is able to dive into details.

**Comment by datavinci-audits** [comment]
Apologies.
There hasn't been any change on the site. I would appreciate your help in diagnosing the problem better.
Thank you

**Comment by jissereitsma** [comment]
If there are no changes made to the site, then there should not be any changes to the files of this extension that are part of your site either. If you want to debug, enable the debug settings in this extension, place an order and see if there is a `purchase` event. If you don't see any purchase event in the browsers error console, consult the person who built this shop to find out why this is so, or dive into the technical situation yourself. If you do see a purchase event in the browsers error console, you can close this ticket - because then this extension simply just worked after all.

**Comment by jissereitsma** [comment]
@datavinci-audits  I see that you closed this issue. Does this mean that the extension worked?
