### ISSUE TITLE
Magento 2.2 compatibility

### ISSUE THREAD

**Issue by tdgroot** [yireo/Yireo_GoogleTagManager2#26]
What would be the minimum effort to make the module Magento 2.2 compatible? 

Changing the `magento/module-catalog` version to `102.0.*` in composer.json would be a great start, but I'm not sure if the codebase is compatible with 2.2. Once the module is M2.2 compatible, things like ViewModels can be implemented the way Magento designed it. 

Anyone has any ideas? I'm trying to get this going.

**Comment by jissereitsma** [comment]
Actually, I have been already using this extension under Magento 2.2 without issues, but because of a locally modified `composer.json` file. I have now released a new version 0.3.5 to accommodate this change: https://github.com/yireo/Yireo_GoogleTagManager2/commit/846cd1bc4cf709611b46347ca8f7f9c6824edd49#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by tdgroot** [comment]
Good to know, thank you!
