### ISSUE TITLE
Triggering AJAX call on each event when typing in the email address field in the checkout

### ISSUE THREAD

**Issue by amenk** [yireo/Yireo_GoogleTagManager2#64]
When typing in the email address in the checkout email address field, on each keypress a request ist triggered.

Is this normal?

Request URL: /customer/section/load/?sections=yireo-gtm-quote%2Cyireo-gtm-order&_=1572343705842

**Comment by jissereitsma** [comment]
No, that would not seem to be normal to me. However, first of all, a default Magento instance does not have any on-keypress validation of an email address. So this seems to be some kind of checkout customization that is causing any kind of validation to begin with. Second, our GTM extension is not doing any type of validation of forms either. It simply responds to the `customerData` changes. So it seems to me that you are bumping into the fact that another extension is causing the `customerData` object to be updated with any key press, and because of this, an extension like the GTM will need to update its own data as well.
