### ISSUE TITLE
Cannot find module config m2 2.3.3 

### ISSUE THREAD

**Issue by AlexanderSk** [yireo/Yireo_GoogleTagManager2#68]
Hello, after enabling the module and recompiling the whole m2 and logging of the admin and on and of course checking if module is enabled in the setup i cannot find the module configuration :S

i go to Stores -> (settings) configration-> Sales tab and there is nothing there :(
Any thoughts please?

![2019-12-10_10-23-09_explorer](https://user-images.githubusercontent.com/2542688/70508415-15232f00-1b37-11ea-90ce-a1dbacd9b0de.png)

Best regards,
Alexander

**Comment by jissereitsma** [comment]
The following file is correctly adding the GTM section to the tab **Sales**: https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/etc/adminhtml/system.xml This works for all others. So I don't know what is wrong ... I'm assuming that you are trying to get this result on a production environment (and not a development environment) because you mentioned code compilation. Perhaps it is safer to get things up and running in a development environment first? Also, could you provide more details: Deployment mode, PHP version, Magento version, confirmation that the module is enabled (output of the command `bin/magento module:status --enabled | grep Yireo`) and anything else.

**Comment by AlexanderSk** [comment]
Hello, thank you for your time.
Yes it is a production enviroment in a website i have recently undertaken...

bin/magento deploy:mode:show
Current application mode: production. (Note: Environment variables may override this value.)

bin/magento module:status --enabled | grep Yireo
Yireo_GoogleTagManager2

php -v
PHP 7.2.24 (cli) (built: Oct 30 2019 15:08:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.
    with Zend OPcache v7.2.24, Copyright (c) 1999-2018, by Zend Technologies

bin/magento --version
Magento CLI 2.3.3

:)

**Comment by jissereitsma** [comment]
I honestly don't know what could be wrong. I assume you are logging in with an admin user that has all needed privileges in its role. Other than that, I wouldn't know what is wrong ...

**Comment by AlexanderSk** [comment]
Hi, just for the record indeed i had developer account in the website...
When i became admin i saw the menu. But why not to show this menu for devs anyway ;)

thank you and have nice holidays!

**Comment by jissereitsma** [comment]
Thanks. I wouldn't know what was wrong. But glad you got things sorted anyway.
