### ISSUE TITLE
Preview with Debug from GTM does not connect

### ISSUE THREAD

**Issue by finamateo** [yireo/Yireo_GoogleTagManager2#74]
When using the Google Tag Manager extension, it does not show the debug feature from the Preview function on GTM. It runs time out trying to connect.

**Comment by jissereitsma** [comment]
Thanks for posting. What do you mean with running a timeout when connecting? Are you seeing some error? And which domain is GTM trying to connect to? I assume it is a public domain?

**Comment by jissereitsma** [comment]
I googled around. Are you sure the following article is not mentioning any solution? https://www.analyticsmania.com/post/google-tag-manager-preview-mode-not-working/ I really am not sure if you are addressing an issue with this extension or that you are looking for general GTM support. I'm not a GTM expert, it is just a Magento extension. But this assumes that you are going all the way in troubleshooting the GTM part of the extension.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.

Note that a new version of this Yireo GoogleTagManager (v3) was released with GA4 support, full checkout support and completely event-driven. It could fix the issue that you were having.

Also note that there is a complete guide also which you can use to setup things: https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/TUTORIAL.md
