### ISSUE TITLE
Didn't work in the custom payment method

### ISSUE THREAD

**Issue by pfgianoto** [yireo/Yireo_GoogleTagManager2#87]
I have a payment gateway and the ORDER data layer didn't show up on the success page in this custom payment method, in other everything works. Take a look in print. Any help how can I set the ORDER data layer to show in this payment method?

![Screenshot_2](https://user-images.githubusercontent.com/9287243/155607304-7ac74933-2fd3-4324-ac3c-ae380473339b.png)

Sorry, I had to erase the store name due to a confidentiality agreement signed.

**Comment by jissereitsma** [comment]
I don't understand the problem really. The page you are describing seems to be a custom page, served by a custom module with custom XML layout and everything. Did you actually look into the GTM module its XML layout and logic? Because it seems you are simply looking for duplicating that, so simply duplicate it. Note that to do this, you need to be a Magento developer with knowledge of Blocks, XML layout and the checkout logic.

**Comment by pfgianoto** [comment]
We are using a very popular payment method in Brazil. GTM does not apply datalayer when using this specific payment method.
But it's ok, I apologize. I thought I could get some help here.

**Comment by jissereitsma** [comment]
I'm just a single volunteer maintaining this package and I'm not any kind of Brazilian payment method and unable to test for. It's really not smart to ask me to pick up on this task. But as Magento can be implemented with certain knowledge, that knowledge (XML layout, PHTML templating, debugging, configuration reading - the basic stuff) can be used to implement this. And I'm happy to see a PR for this.

As mentioned, it might be as simple as duplicating things. But if you are thinking this might be complex, it might simply be that you are looking to implement a feature without diving into it - and then, yeah, I'm unable to help there.

**Comment by jissereitsma** [comment]
I'm closing this issue, because as of yet, it seems a request for help that is so specific to the Brazilian market that you need to be diving into this payment method with a Brazilian shop to make it a success. Unfortunately, I'm not Brazilian and I'm not using that payment method, so I'm unable to help. And because the question seemed to be asked in a way that can only be answered by me providing that solution, I'm afraid no one is picking up on this anymore :(
