### ISSUE TITLE
Success page dataLayer variables overwritten

### ISSUE THREAD

**Issue by jmassey** [yireo/Yireo_GoogleTagManager2#91]
Hi All,

Debugging dataLayer variables with google TagManager preview, he have detected that in success page, dataLayer variables like:

transactionId -> goes to undefined
transactionTotal -> goes to 0
transactionProducts -> empty

gets overwritten by quote data instead of order data, so order data is lost.

We have modified afterGetSectionData function in addToCartSection pluguin

```php
public function afterGetSectionData(CustomerData $subject, $result)
    {
            **$quoteId=$this->getQuoteId();**
        if (empty($result) || !is_array($result) || **!isset($quoteId)**) {
            return $result;
        }
```

Projects are hyva based.

Thanks.

**Comment by jissereitsma** [comment]
Thanks. Commit https://github.com/yireo/Yireo_GoogleTagManager2/commit/5908796f8f8159745b647ddfea2aaa587bb62445 has now added this fix.

Please note that a PR is very easily made with GitHub: Edit the file, done. It makes it easier to talk about which code is modified how, instead of copying and pasting, which might contain errors. But thanks for the suggestion!
