### ISSUE TITLE
Yireo GTM shows incorrect readings in Analytics

### ISSUE THREAD

**Issue by EWIM-rick** [yireo/Yireo_GoogleTagManager2#96]
Hey Yireo, 

We're using Yireo Google Tag Manager in our store. This was installed after an update where our last GTM was no longer supported. 
The extension set's up the tracking, but the values are WAY off. We're seeing sales in the thousands range in Magento Back End, but Analytics shows Millions. it's not simply multiplying as far as I can see.

Have you seen this before?

Kind Regards, 

Rick

**Comment by jissereitsma** [comment]
Thanks for reporting this. Looking at the CHANGELOG I can't see any change that would suggest this. Also, your report for "things being way off". Could you come with one specific example? Have you also double-checked all of the other aspects involved? For instance, is your GTM receiving data? Is the success page still working (or crashing with some other cause)? Unfortunately, as of yet, this issue is far too broad for an open source project support to do something useful.

**Comment by EWIM-rick** [comment]
Yeah I get this is very broad, there is data flowing into Analytics, so I concluded that the installation basics were working. 
The site seems to be working fine. I don't see any lead that 

The tracking for some products seems right, but there are a lot of products that are begin sold much more (according to analytics) for a lot more money. 

If we can we open any private line of communication I could share images. They would be from a live shop so I wouldn't like to share them in public. 

In example there is a product that is configurable that now has an average price in analytics of € 2.336.591,40 from 1 sale. 
The single sale for that item in that period was total incl tax of € 929,49 

Total in sales that month is around € 27000,-

I can't relate this behavior to anything. 

Kind regards, 

Rick

**Comment by jissereitsma** [comment]
This ticket has gone quiet, so I'm not sure how this was solved. Looking back at the earlier issue, I would say that it is strange that **any** sales was reported in your Google Analytics, because the earlier version of this Magento extension did not have any Enhanced Ecommerce solution, so no sales would be reported.

Note that a new version of this Yireo GoogleTagManager (v3) was released with GA4 support, full checkout support and completely event-driven. It could fix the issue that you were having.

**Comment by jissereitsma** [comment]
I'm closing this ticket as of yet, because of inactivity. If this is still a problem, feel free to re-open or post a new Issue.
